language: bash

before_install:
  - sudo apt-get update
  - sudo apt-get install -y octave octave-image octave-pkg-dev git python-pip unzip

# command to install dependencies
install: 
  - wget https://github.com/stegro/hdf5oct/archive/b047e6e611e874b02740e7465f5d139e74f9765f.zip
  - unzip b047e6e611e874b02740e7465f5d139e74f9765f.zip
  - pushd hdf5oct-* && make && sudo make install && popd
  - wget https://github.com/bats-core/bats-core/archive/v0.4.0.tar.gz
  - tar -zxf v0.4.0.tar.gz
  - pushd bats-core-0.4.0 && sudo ./install.sh /usr/local && popd

# command to run tests
script: make test

